#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GroteKerk.Resource", IsApplication=true)]

namespace GroteKerk
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int accent = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int bg_screen_1 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int bg_screen_2 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int bg_screen_3 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int bg_screen_4 = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int primary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primaryDark = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int window_background = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int btn_next = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int btn_skip = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int imageView1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int layoutPanel = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int viewPager = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layoutSlide1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layoutSlide2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int next = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int skip = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int slide_1_text = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int slide_1_title = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int slide_2_text = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int slide_2_title = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int start = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int KerkThema = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
